services:
  - type: web
    name: nusrat-furniture-payments
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AUTO_CREATE_DB
        value: "1"
      - key: DATABASE_URL
        sync: false
